# Site settings
title: Kahuna Coder
email: ghp@kc.gs
description: "Building web sites since 1995"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CDB6A0 #9A645D
  secondary: 541935 #9A7B5D
  secondary-dark: 174B24 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 2505 Kipuka St
  
  - line: Koloa, HI 96756

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:categories/:title.html

tag_page_layout: tag_page
tag_page_dir: technology

category_dir : industry
category_title_prefix: 'Industry: '