# Site settings
title: Kahuna Coder
email: ghp@kc.gs
description: "Building web sites since 1995"
url: "http://www.kahunacoder.com"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CDB6A0 #9A645D
  secondary: 541935 #9A7B5D
  secondary-dark: 174B24 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/kahunacoder
  - title: facebook
    url: https://facebook.com/kahunacoder
  - title: linkedin
    url: https://www.linkedin.com/in/kahunacoder
  - title: bitbucket
    url: https://bitbucket.org/kahunacoder
  - title: github
    url: https://github.com/kahunacoder

# Postal address (add as many lines as necessary)
address:
  - line: Cocoa, FL 32926 
  
#  - line: Koloa, HI 9675

#FL
resume: https://docs.google.com/document/d/1slAZ5pF7Ai1oxN0Vv_kyvB_mKijH2nfQDWk922VxTJ4
#HI
#resume: https://docs.google.com/document/d/1GCigF2vNoX6sbGeT4Tewy1DdX8l11Kdwo0yC3W8cCIQ

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /industry/:categories/:title.html

tag_page_layout: tag_page
tag_page_dir: technology

category_dir : industry
category_title_prefix: 'Industry: '

gems:
  - jekyll-sitemap
